language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: all.git@am.id.lv
  api_key:
    secure: GmqvWCMP3IjFIZF/owfzIE6yYK3n9Zv8S5/ayJ/x1lO3rBxUGRQb5dlIIRAx+l37vjDvnUZfp1DkiB+gniY7MkNYiXVaZkYN8Ja2VeYmwBjyrETjAbCMKwmJ2N3o+UoV/BKxcAQqbU5/fimw5O/Zui8Bhh6DHtR1vpU630E1Lmo+Je20XSHuVT/rwajJZ6aUGEHzp9PXRQp4esBN6n04muEL5WbOEg67Q8CqzB1C0QjQ04OaQ62OPOoGwqk8IWKcU+zb++5DJ7KN/JhHwIu/eMRs/lmix6MD9Pm2pbPaRa9ISEd3YhtHmnSJauAbSUgVJsMlvtb16J3FJxVU4q60or7wBwPCseODLUZl776QwpS0CiPOj1fRnpkrXBXQdvfjxQ8KvArpe+ZotJLCYqyO3x91whmuMErMp3fwYjy3b5vy6+pWFSjwYr3TwxbNYuDes3IPLSg8mpROX2Eyebn6L3/gcGkuOzVeutx/JW9aVPVxssHj5cXGLIn+AAEelrthc3/6YjcOgTCDMsg6kTgV5byhQSmwoOyZaUFvM1HCRFGsODC6dWjUjLIdUk1EX//iXPRdknKXSIFDtA4PUvfLEkVD2az+5A8YjUiLrdgRNyQGEwnl9DiCkTeoZBBhpS5MOpmgdYkASf9EqEEpoEg0GbvPSfVxpybIka9ZRtSl+AI=
  on:
    repo: maximandrewz/maze-solver
