language: node_js

node_js:
  - "6"

deploy:
  provider: npm
  email: all.git@am.id.lv
  api_key:
    secure: pkwuZ9ubm3brmXiCGds5beHEEa/9l4y9w4pP1N2FSYzvVly9gU+iZVkIIVgHS3yArZDN/+ZWqSwsYjm/b4pwvsPckbdKC5n8J6O45CscyoUkql8H45CsCrcV3nr/qRnlOBApv6s8diNx70o5swES4k0HhQdl82xMkcAL+lir0pfv9Jf5SvwntOVayjjojSilVqzmJU3RdWeawaiPHOdK4RydbLEvGgvm8C6yDbwcotRdFN4/H9dFBJCD0pt2MtjUoW3bJm3dS7miVD95P6TdvteLmLHIMgK2+J7YNaetGqcgWCvgoNphlvuC/tUfHh7ThSFIICyFzXb/JNRVarOZopPQryArZE2W/wM8GPT/85wKGbzIHD0s2FVWNgbtORCWLPA6PEA7O6d2zLjlPfwBYnxsQpXV4TVq3NlPlTbFgIdgiwYy4UKy1Uyp/9V8HslqHtgBxhJRuMFAOGCtducLC+03V6C2lxCNR/RTe2JzszEec7iuaOjTqdrgeKSV4DOshzWn2kLYqdwIgNKoZfN+CfFydi0bCwhiI021JU5PD9EB+Eyy0eY/A3AWvxzYiW6Qt9OISVjQrlL/Ezfd9TMHtaMn2+la+RBgOa8YObbgSTGCDZz2WKRUxu+KJkq8h08mFFmicAM65lvMnl1bauZvWBi0sPH6sUHB82sooTGLD7k=
  on:
    repo: maximandrewz/fscopy
